apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: tasks-api
    newName: ghcr.io/avjpl/tasks-api
    newTag: initial
  - name: tasks-web
    newName: ghcr.io/avjpl/tasks-web
    newTag: initial
