apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tasks-app
  namespace: tasks-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    name: tasks-app-secrets
  data:
    - secretKey: MONGODB_ROOT_PASSWORD
      remoteRef:
        key: MONGODB_ROOT_PASSWORD
    - secretKey: MONGODB_URI
      remoteRef:
        key: MONGODB_URI
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: REDIS_PASSWORD
    - secretKey: REDIS_URL
      remoteRef:
        key: REDIS_URL
