apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: doppler-secret-store
  namespace: tasks-app
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: dopplerToken
